apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: standard-managed-disk-pvc
  namespace: dev3
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi      

# AKS already provisioned Storage classes managed-premium and default as part of 
# default cluster setup      
