apiVersion: v1
kind: Pod
metadata:
  name: sysctl-busybox
spec:
  securityContext:
    sysctls:
    - name: net.ipv4.tcp_keepalive_time
      value: "120"
    - name: net.ipv4.tcp_keepalive_intvl
      value: "60"
    - name: net.ipv4.tcp_keepalive_probes
      value: "30" 
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'sleep 1048']

